### ISSUE TITLE
Discuss Center deletion on_delete method

### ISSUE THREAD

**Issue by jamienoss** [RISPaDD/biospecdb#300]
Options:
 * When a center is deleted ALL related items get deleted with it (``CASCADE``):
   * patient data
   * user
 * Centers can't be deleted since their relations are protected (``PROTECT``)
   * all related patient data must first be deleted
   * all related users must be deleted

**Comment by jamienoss** [comment]
@Alvaro-FG I know we've discussed this before, but now that we're going live, I want us to discuss it one last time, please.

**Comment by Alvaro-FG** [comment]
I believe we discussed the second, as deleting all patients first in bulk could be done "easily" by filtering them by centre (same with users) and then once empty the centre can be deleted. It is a matter or preventing someone (aka me) from messing it all up. Does that make sense?

**Comment by jamienoss** [comment]
@Alvaro-FG Perfect! Thanks for the quick response.
