### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by Alvaro-FG** [RISPaDD/biospecdb#319]
When creating new patients, visits, observations, etc. depending on the number of data that is filled, it might prompt to which data is required and has not been filled (good) but also sometimes it throws a server error 500. Several combinations seem to throw that error but a simple one is try to add an observation, do not fill any of the fields and try to save it.

**Comment by jamienoss** [comment]
@Alvaro-FG Hey, this might be related to #327 so let's observe this further.

BTW, if you get a 500 (internal server error) can you at least post the timestamp (UTC) for when this occurred, please? Better still if just after it happens you find it in the AWS application logs, can you post the link for the erroring line in the AWS application log, please?

FYI I wouldn't suggest posting the error itself, in case there's something in there that shouldn't be publicly displayed here. At the moment, during this beta testing transition phase there shouldn't be, but still. Might be safer for you to adopt a blanket approach of not doing so.

**Comment by jamienoss** [comment]
This can be reproduced when trying to save a new and empty observation form.
https://github.com/RISPaDD/biospecdb/blob/main/biospecdb/apps/uploader/models.py#L474
```python
if self.observable.center.count() and (self.visit.patient.center not in self.observable.center.all()):
            # Note: Don't expose centers here.
```
but obviously `` self.observable`` doesn't exist. This should have been handled by the individual field validations prior to ``clean()`` being called. 🤔
