### ISSUE TITLE
Small sample name 

### ISSUE THREAD

**Issue by Alvaro-FG** [RISPaDD/biospecdb#320]
In the patients window, next to Sample Type there is a small sample written next to the sample type scroll menu, but the is broken down in three parts Sa/mp/le

**Comment by jamienoss** [comment]
<img width="1121" alt="Screenshot 2024-04-16 at 9 47 12 AM" src="https://github.com/RISPaDD/biospecdb/assets/5013975/4fad14aa-41a6-4035-b109-bba20b6c08be">
